### ISSUE TITLE
Empty: Failed to retrive number of trained models

### ISSUE THREAD

**Issue by kamil-safin** [machine-intelligence-laboratory/TopicNet#12]
I installed topicnet through pip and have 'Empty: Failed to retrive number of trained models' when trying to run my_first_cube(tm, data) from guide

**Comment by Evgeny-Egorov-Projects** [comment]
Hi there!

Seems like in your case our multithreading approach failed to finish training a model before the program tried to extract it to the parent process. A quick way to fix this issue would be to use 
`my_first_cube(tm, data, separate_thread=False)` option. Could you, please tell a bit more about the dataset you used and the system you trained it on?

**Comment by kamil-safin** [comment]
Hi
I use dataset of chat conversation with about 6k short dialogues. My system is MasOS with topicnet==0.4.1. I'm following your guide but use my own dataset.
And now I have:
`InvalidOperationException: TopicKernelScoreConfig.class_id @bigram does not exists in n_wt matrix`

**Comment by Evgeny-Egorov-Projects** [comment]
Did you use our preprocessing guide?
Can you confirm that you have modality named '@bigram' in your dataset? 
If you have that modality can you check if it is not empty?

**Comment by kamil-safin** [comment]
Yes, I used
Example of single line in dataset ('vw_text' field):
`6 |@lemmatized подать:1 новый:1 заявка:1 |@bigrams подать_новый:1 новый_заявка:1`
How can check the existence of modality in my model?

**Comment by kamil-safin** [comment]
sorry, my bad:
used '@bigram' and '@bigrams' in different places of code
thanks for `separate_thread ` solution!
