### ISSUE TITLE
dataset_batches folder contains not only batches, but also vw.txt and dict.dict

### ISSUE THREAD

**Issue by Alvant** [machine-intelligence-laboratory/TopicNet#21]
![dataset_batches](https://user-images.githubusercontent.com/15067981/74127493-de779c80-4beb-11ea-9abd-1b733b10c5c5.png)

**Comment by Alvant** [comment]
A bit confusing...

**Comment by Alvant** [comment]
220

**Comment by Evgeny-Egorov-Projects** [comment]
Ч,ё это за цифры?


вт, 24 мар. 2020 г. в 22:18, Vasiliy <notifications@github.com>:

**Comment by Alvant** [comment]
Номера реквестов на Битбакете)

**Comment by Alvant** [comment]
Done, waiting for the release
