### ISSUE TITLE
Где можно скачать датасеты на которые ссылаются нотбуки?/ Where can I get datasets referred to in demo notebooks?

### ISSUE THREAD

**Issue by sladkoejka** [machine-intelligence-laboratory/TopicNet#32]
Где можно скачать датасеты на которые ссылаются нотбуки?
wiki_data/wiki_data.csv
topicnet/PScience.csv
data/lenta_1000_100.csv

**Comment by Evgeny-Egorov-Projects** [comment]
Привет! Спасибо за вопрос, нам очень не хватает отзывов от пользователей.
По сути вопроса: 

1. data/lenta_1000_100.csv не закачивается и не устанавливается через `pip`, но саму коллекцию можно найти [здесь](https://github.com/machine-intelligence-laboratory/TopicNet/tree/master/topicnet/demos/data/lenta_1000_100_batches) (файл vw.txt загружается через датасет)
2. Предполагалось, что коллекцию на википедии пользователь получит после того как запустит [ноутбук](https://github.com/machine-intelligence-laboratory/TopicNet/blob/master/topicnet/demos/RTL-WIKI-PREPROCESSING.ipynb), где рассказывается про базовую предобработку текстовых данных.
3. Коллекция PScience  действительно отсутсвует, мы планируем в ближайшее время сделать доступными набор коллекций для моделирования включая тексты из ПостНауки.

**Comment by sladkoejka** [comment]
Большое спасибо, за быстрый ответ) 
но ноутбук по википедии. не загружает данные, выскакивает ошибка при попытке загрузить датасет 
![image](https://user-images.githubusercontent.com/41921144/76322313-4bb64480-62f4-11ea-95b8-2f77c856d091.png)

**Comment by Evgeny-Egorov-Projects** [comment]
Значит сегодня несчастливый день - [сайт исследовательской группы раздававшей датасет](https://www.dice-research.org/Palmetto) лежит. Я заархивировал копии датасетов с наших серверов, посмотри если получится запустить на них: 
[PScience.zip](https://github.com/machine-intelligence-laboratory/TopicNet/files/4313222/PScience.zip)
Вики вышла чуть больше - вот [ссылка на гугл драйв](https://drive.google.com/open?id=1-PyRlwDnk3cqH8DidQqvHJ9uJtPazC2o)

**Comment by Evgeny-Egorov-Projects** [comment]
A recap for users not familliar with Russian:

**Comment by sladkoejka** [comment]
Ещё вот этого файла не хватает
topicnet/subtitles.csv
он используется в ноутбуке PrettyDemo, рядом с PScience.csv

**Comment by Evgeny-Egorov-Projects** [comment]
Тот ноутбук основательно устарел - он делался еще до первого релиза библиотеки. Конкретно тот датасет не лучший для тематического моделирования и использовался только из-за одного достоинства: он маленький (чтобы быстро тренировать модели). Сам ноутбук или удалим (если на него нигде не ссылаемся) или переработаем.
