### ISSUE TITLE
error ModuleNotFoundError: No module named 'topicnet.cooking_machine.recipes'

### ISSUE THREAD

**Issue by sladkoejka** [machine-intelligence-laboratory/TopicNet#34]
from topicnet.cooking_machine.recipes import ARTM_baseline
Notebook: 20NG-GenSim vs TopicNet

![image](https://user-images.githubusercontent.com/41921144/76426252-dc0b8c80-63bb-11ea-8a50-45a5c1bc302d.png)

**Comment by Alvant** [comment]
Привет!

Спасибо, что сказал о баге.
Да, мы тоже недавно это заметили, что рецепты потерялись :(
Недавно поправили https://github.com/machine-intelligence-laboratory/TopicNet/releases/tag/v0.6.1
Можно переустановить ТопикНет, и всё должно быть Ок
