### ISSUE TITLE
error  in 20NG-GenSim vs TopicNet

### ISSUE THREAD

**Issue by sladkoejka** [machine-intelligence-laboratory/TopicNet#35]
[Errno 21] Is a directory: '20_News_dataset/train_preprocessed.csv'

тут как я понял создаётся папка для логирования, я на всякий случай создал свой путь 
EXPERIMENT_PATH = 'test//'
но ошибка осталась 

![image](https://user-images.githubusercontent.com/41921144/76430762-bd0ff900-63c1-11ea-95e6-4bf8bf31c5f7.png)

**Comment by bt2901** [comment]
А на какой именно строчке вылетает? Можно Traceback?

**Comment by sladkoejka** [comment]
Да, препроцессинг перевыполнил, запустилось. Спасибо.

**Comment by sladkoejka** [comment]
Понимаю, что не ваш сервис, но онлайн сервис для определения когерентности теперь не работает. Только локально теперь запускать
![image](https://user-images.githubusercontent.com/41921144/76498430-e8d8c080-644d-11ea-88ae-8c024b5304a1.png)

**Comment by Evgeny-Egorov-Projects** [comment]
Боюсь быстро и "из коробки" мы тебе тут не поможем. 
Можешь 
1) поискать реализации по гитхабу 
2) разобраться как считать совстречаемости в BigARTM и написать такую метрику самому.
Если всё пойдёт идеально то недели через 2-3 у нас появится такой код в ветке разработки либы (мы тоже не хотим зависеть от онлайн сервисов оценивая свои модели).  Вот [гайд](https://bigartm.readthedocs.io/en/stable/tutorials/python_userguide/coherence.html) из документации библиотеки, к сожалению по нему мы пока ничего не делали (реализуй на свой страх и риск).

**Comment by bt2901** [comment]
Я спросил у ребят из dice-group: https://github.com/dice-group/Palmetto/issues/38#issuecomment-599206759

Они делают большой оверхаул своей инфраструктуры, поэтому пока что не всё работает. В будущем всё это починится.

Если подсчёт когерентностей нужен прямо сейчас, то [вот в этом ноутбуке](https://github.com/machine-intelligence-laboratory/TopicNet/blob/master/topicnet/demos/Making-Decorrelation-and-Topic-Selection-Friends.ipynb) есть подсчёт когерентностей через совстречаемости. 

Замечу, что это происходит  на том же корпусе, что и модель, а Palmetto вычисляет совстречаемости на внешнем корпусе (английская Википедия). Это актуально, например, для не-английских корпусов или корпусов с сильно специфичной лексикой.

**Comment by sladkoejka** [comment]
Спасибо, как раз с этим ноутбуком разбираюсь) 
Жаль, что нигде нет видео-инструкции как этот файл запускать

**Comment by Evgeny-Egorov-Projects** [comment]
Привет еще раз. Мы (команда лаборатории) хотим сейчас собрать все пожелания к улучшению библиотеки в одном месте и естественно не могли пройти мимо такого активного пользователя как ты! Предлагаю написать мне на почту (egorov.eo@mipt.ru) удобное время и канал общения. Я позадаю вопросы про то как и зачем ты использовал библиотеку, что было тяжело\непонятно и всё в таком духе.
