### ISSUE TITLE
Не выполняется код в Making-Decorrelation-and-Topic-Selection-Friends

### ISSUE THREAD

**Issue by sladkoejka** [machine-intelligence-laboratory/TopicNet#37]
Может быть вопрос и не к вам, но вы наверняка с этим сталкивались. 

Я не могу понять как мне запустить скрипт, для подсчёта совстречаемости. 

вот этот код
cd <working_directory path> && <путь к папке, в которой находится bigartm>/bigartm/build/bin/bigartm \
    -c train_vw_natural_order.txt \
    -v vocab.txt \
    --cooc-window 10 \
    --cooc-min-tf 1 \
    --write-cooc-tf cooc_tf_ \
    --cooc-min-df 1 \
    --write-cooc-df cooc_df_ \
    --write-ppmi-tf ppmi_tf_ \
    --write-ppmi-df ppmi_df_

Я в линуксе не могу найти где вообще этот терминал bigartm, т.к. в самой папке с библиотекой где он находится и близко нет (/bigartm/build/bin/bigartm ) , но я устанавливал её просто pip install bigartm10 
Я пытался на windows запустить, там ваша библиотека не устанавливается, но я скопировал все файлы 
вот эта строчка выполнилась -c train_vw_natural_order.txt даже что-то создала, а остальные ни в какую, я их пробовал и построчно запускать и всё вместе в одну строку как тут указано https://bigartm.readthedocs.io/en/stable/tutorials/bigartm_cli.html

Но всё это тоже не работает, вы это как-то запускали, расскажите, что я делаю не так? 
Может дело в том, что нужно было bigartm не через pip устанавливать...

**Comment by Alvant** [comment]
tl;dr Да, @sladkoejka, вы правы! При создании ноутбука эта тулза для командной строки создавалась на машине вручную. То есть `pip install topicnet` или `pip install bigartm` не хватает для запуска ноутбука на 100%. Вот инструкция по более "суровой" установке АРТМ https://bigartm.readthedocs.io/en/stable/installation/index.html, которая обеспечит наличие `bigartm/build/bin/bigartm` (уж на Линуксе точно). 

Это пример команды. Да, дело в том, что БигАРТМ умеет работать с совстречаемостями, но только через командную строку.

Нужна так называемая [bigartm command line utility](https://bigartm.readthedocs.io/en/stable/tutorials/bigartm_cli.html).
Чтобы она появилась, например, на Линуксе, нужно собрать АРТМ вручную, как описано [тут](https://bigartm.readthedocs.io/en/stable/installation/index.html) (там же есть и раздел для Windows). И тогда нужная тулза будет лежать примерно по такому пути (по крайней мере, на том же Линуксе) `<путь, куда скопировали bigartm репозиторий для ручной сборки>/bigartm/build/bin/bigartm`.

Действительно, об этом стоило сказать подробнее в ноутбуке! так как при `pip install topicnet` на машине не появляется нужной АРТМ утилиты: `pip install topicnet` подтягивает `artm`, но вроде только в виде .py файлов (*без* запускабельного бинарника).

Но вообще, если на разбирание с совстречаемостями будет уходить много времени, то ноутбук можно запускать и без них: это "самый тонкий" момент, но совстречаемости в принципе не обязателены, ноутбук писался так, чтобы можно было обойтись и без них. Хотя совстречаемости, конечно, хорошо бы иметь для оценки тем.

И на Windows, увы, `topicnet` пока не ставится через `pip`. Но это в планах.

**Comment by Alvant** [comment]
Да, забыл уточнить: не обязательно именно устанавливать АРТМ целиком. Достаточно дойти до команды `make` в инструкции по Линуксу: после её выполнения уже должна быть утилита `bigartm`, которую можно использовать

**Comment by sladkoejka** [comment]
Спасибо, скрипт запустился, изучаю дальше)

**Comment by Alvant** [comment]
Отлично!)
