### ISSUE TITLE
Invalid root folder name for Windows

### ISSUE THREAD

**Issue by Gernar** [machine-intelligence-laboratory/TopicNet#42]
when I init the experiment, it tries to create a folder with illegal symbols in the name. 
`experiment = Experiment(experiment_id="simple_experiment", 
                        save_path="experiments", 
                        topic_model=topic_model
                       )`

and I get 
`
OSError: [WinError 123] Синтаксическая ошибка в имени файла, имени папки или метке тома: 'experiments\\simple_experiment\\<<<<<<<<<<<root>>>>>>>>>>>'
`

I tried to change "model_id" manually,  `topic_model.model_id = 'root'` but it change nothing.

**Comment by bt2901** [comment]
Somehow, we had no idea that "<" is illegal in Windows! This will be fixed in the next release.

A quick workaround is to edit the `padd_model_name` function in the `topicnet/cooking_machine/model_tracking.py` file.

Replace this line:
``` 11         return '<' * add + model_id + '>' * (add + odd)
```
With this:
```
 11         return '#' * add + model_id + '#' * (add + odd)
```

**Comment by Evgeny-Egorov-Projects** [comment]
Should be fine now
