### ISSUE TITLE
Takes a lifetime to initialize a really big Dataset

### ISSUE THREAD

**Issue by Alvant** [machine-intelligence-laboratory/TopicNet#45]
1. Create some big .csv (several 100k rows should be enough; maybe fewer also ok)
2. Try do `dataset = Dataset(csv_table_path, keep_in_memory=False)`

![too-long](https://user-images.githubusercontent.com/15067981/79639878-03adfb80-8197-11ea-8775-9cdfda680053.png)

Result: dataset is not ready after reasonable amount of time

P.S.
After this one fixed, one should check that `dataset.get_batch_vectorizer()` also is not too slow

**Comment by Evgeny-Egorov-Projects** [comment]
Can you confirm that its due to our code or because of dataset backend?
As far as I know, It is due to dask setting itself up.

**Comment by Alvant** [comment]
Нет, это из-за логики создания датасета.

Прикрепил картинку: видно, что он читает модальности, и это тянется очень долго (я свой датасет так и не дождался 😊). Чтоб узнать все модальности, он итерируется по всем строчкам датафрейма. И в случае даска (да и вообще 100k строчек текста само по себе считать уже не мало, документы ведь могут быть большими) это вообще не вариант.

Сам даск уже создался (строчка с вытягиванием модальностей идёт после даска).

То есть надо, похоже, как-то менять логику выяснения всех модальностей в датасете.

**Comment by Evgeny-Egorov-Projects** [comment]
Ок, понял. По-моему это была паранойя что первая строчка (вдруг) не содержит все модальности.

**Comment by Alvant** [comment]
Да, похоже, что так. Но если при даске и 100 строчек будут читаться долго (надо проверить), то мб стоит вообще требовать указание модельностей при инициализации датасета, хотя бы в случае даска `Dataset(keep_in_memory=False, modalities=[...])`.

Ещё + к задаче максимум: можно прикрутить кэши для функций `get_vw_document()` и `get_raw_document()`, чтобы запоминались тексты N последних документов. И тогда, если ещё раз поступает запрос на документ из кэша, то результат выдаётся быстро (в обход даска). Это может быть полезно в целом, и ещё для некоторых скоров (когерентности)

**Comment by Alvant** [comment]
This one should be fixed already. One need to check (just in case) and the issue may be closed

**Comment by Evgeny-Egorov-Projects** [comment]
Fixed in 0.7.0
