### ISSUE TITLE
Refactor of `reg_search` and `tracked_score_function`

### ISSUE THREAD

**Issue by bt2901** [machine-intelligence-laboratory/TopicNet#6]
`tracked_score_function` should have default value of `"PerplexityScore@all"`. Also, possibly it should be an attribute of `Strategy` instead of `Cube`.

`reg_search` should be renamed into something more informative. Also, possibly it should be an attribute of `Strategy` instead of `Cube`.

**Comment by Evgeny-Egorov-Projects** [comment]
`tracked_score_function` refactored and has a default score value in develop branch. Will bring it here as other issues resolved
