### ISSUE TITLE
Dataset_manager - Connection refused

### ISSUE THREAD

**Issue by DmitriyValetov** [machine-intelligence-laboratory/TopicNet#74]
Что-то из колаба dataset_manager не может достучаться до вас:
URLError: <urlopen error [Errno 111] Connection refused>

Код: 
from topicnet import dataset_manager
from IPython.display import display, Markdown
display(Markdown(dataset_manager.get_info()))

Ошибка: 
URLError: <urlopen error [Errno 111] Connection refused>
![изображение](https://user-images.githubusercontent.com/27976850/84385565-79af6b80-abf8-11ea-8f11-396139abe96d.png)

А при таком: dataset_manager.load_dataset('RTL_Wiki') ещё выпадет ошибка с неопределенной переменной в блоке finally: 
UnboundLocalError: local variable 'save_path' referenced before assignment

![изображение](https://user-images.githubusercontent.com/27976850/84385537-6c927c80-abf8-11ea-8262-39df09b834ba.png)

**Comment by Evgeny-Egorov-Projects** [comment]
Привет.
Спасибо за инфу! Мы кое-что меняем у себя на серверах и скорее всего из-за этого поломалсф адрес по которому посылался запрос. Я попробую пофиксить это на своей стороны, если все получится скажу какой адрес нужно прописать в `api.py` чтобы всё снова заработало.

**Comment by Evgeny-Egorov-Projects** [comment]
Хотфикс сейчас такой: найди файл `api.py` в `dataset_manager` и замени значение константы `_SERVER_URL` на https://topicnet-datasets.machine-intelligence.ru

**Comment by Evgeny-Egorov-Projects** [comment]
На моей стороне остались какие-то проблемы с RTL_wiki и stanford_triplets остальное вроде работает.
