### ISSUE TITLE
Thetaless sometimes have troubles with modalities

### ISSUE THREAD

**Issue by Alvant** [machine-intelligence-laboratory/TopicNet#79]
![nans](https://user-images.githubusercontent.com/15067981/87227201-1012b080-c3a2-11ea-874c-550a6915b749.png)

:cry:  `np.ravel(ind > 0)`
:smile: `np.ravel(ind != 0)`

P.S. `0.000000001 != 0` -> Ok?

**Comment by Alvant** [comment]
283

**Comment by bt2901** [comment]
I noticed some problems with saving the regularizer as well; I need to track them down someday as well.
