### ISSUE TITLE
Get document-topic representation

### ISSUE THREAD

**Issue by xinlux97** [machine-intelligence-laboratory/TopicNet#80]
Hi, thanks for your implementation.

I'm wondering can we get document-topic representation and word-topic representations?
For each document or each word, the representation should be a vector with length equal to the number of topics.

Thanks!

**Comment by Evgeny-Egorov-Projects** [comment]
Hi there. 
If you interested in obtaining vectors with their corresponding indices (words in topic or topics in the document) then it can be done by calling `get_phi` and `get_theta` methods from TopicModel (make sure that it is not a DummyModel you are working with). Those methods mainly use the code from BigARTM backbone in retrieving word-topic and topic-document distribution respectively. Note that unlike BigARTM (that uses batch vectorizer) we use dataset class from our library to extract topic-document distribution. Other detail that there are realizations for obtaining those distributions in dense/sparse matrices. Details on that methods can be found [in documentation](https://machine-intelligence-laboratory.github.io/TopicNet/cooking_machine/models/topic_model.html)

**Comment by Evgeny-Egorov-Projects** [comment]
I suggest current issure is resolved
