### ISSUE TITLE
Incorrect link to dataset

### ISSUE THREAD

**Issue by karelin** [machine-intelligence-laboratory/TopicNet#83]
The link to RTL-Wiki dataset provided in RTL-Wiki-Preprocessing.ipynb (http://139.18.2.164/mroeder/palmetto/datasets/rtl-wiki.tar.gz) points to non-existing file (error 404 is returned).

After some search, I've found this one: https://hobbitdata.informatik.uni-leipzig.de/homes/mroeder/palmetto/datasets/rtl-wiki.tar.gz

**Comment by Alvant** [comment]
@karelin Thanks! We will update the notebook.
