### ISSUE TITLE
Downloading `postnauka` dataset produces error

### ISSUE THREAD

**Issue by karelin** [machine-intelligence-laboratory/TopicNet#84]
I've tried to access `postnauka` dataset using `demo_data = load_dataset('postnauka')`

Unfortunately, `topicnet` produced error:

```
HTTPError: HTTP Error 502: Bad Gateway
```

**Comment by Alvant** [comment]
@karelin Thank you for the info! Seems we really do have some problems with the availability of the datasets :sweat_smile: I'll let you know when we fix it.

**Comment by Alvant** [comment]
The trees had time to become covered with foliage and bare again. The Earth went around the Sun for millions of kilometers. The datasets were unavailable, then available, then unavailable again. And now, finally... we have `load_dataset` and `get_info` working as expected!
