### ISSUE TITLE
 Making-Decorrelation-and-Topic-Selection-Friends.ipynb Doesn't work in google colab from scratch

### ISSUE THREAD

**Issue by brothertook** [machine-intelligence-laboratory/TopicNet#87]
!pip install topicnet
TopicNet in /usr/local/lib/python3.7/dist-packages (0.8.0)
`
%%time

enable_hide_warnings()

models = decorrelating_cube(topic_model, dataset)  # TODO: nice cube output?

------------------------------------------------------------------------------------------
To toggle on/off output_stderr, click [here](javascript:code_toggle_err()).

/usr/local/lib/python3.7/dist-packages/dill/_dill.py:1845: PicklingWarning: Cannot locate reference to <class '_ctypes.PyCFuncPtrType'>.
  warnings.warn('Cannot locate reference to %r.' % (obj,), PicklingWarning)
/usr/local/lib/python3.7/dist-packages/dill/_dill.py:1847: PicklingWarning: Cannot pickle <class '_ctypes.PyCFuncPtrType'>: _ctypes.PyCFuncPtrType has recursive self-references that trigger a RecursionError.
  warnings.warn('Cannot pickle %r: %s.%s has recursive self-references that trigger a RecursionError.' % (obj, obj.__module__, obj_name), PicklingWarning)
/usr/local/lib/python3.7/dist-packages/topicnet/cooking_machine/models/topic_model.py:427: UserWarning: Failed to save custom score "ActiveTopicNumberScore" correctly! Freezing score (saving only its value)
  f'Failed to save custom score "{score_object}" correctly! '
`

`enable_hide_warnings()

To toggle on/off output_stderr, click [here](javascript:code_toggle_err()).

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-124-cd369ec9c9aa>](https://localhost:8080/#) in <module>
      2 
      3 best_model, DECORRELATION_TAU = select_best_model(
----> 4     topic_model.experiment, CRITERION, DECORRELATE_SPECIFIC
      5 )

6 frames

[/usr/local/lib/python3.7/dist-packages/topicnet/cooking_machine/models/scores_wrapper.py](https://localhost:8080/#) in add(self, score)
     54     def add(self, score: Union[BaseScore, artm.scores.BaseScore]):
     55         if isinstance(score, FrozenScore):
---> 56             raise TypeError('FrozenScore is not supposed to be added to model')
     57 
     58         elif isinstance(score, BaseScore):

TypeError: FrozenScore is not supposed to be added to model

`

**Comment by Alvant** [comment]
@brothertook thank you for the note!

This is the fixed version of the notebook: https://github.com/machine-intelligence-laboratory/TopicNet/blob/bugfix/fix-datasets-loading/topicnet/demos/Making-Decorrelation-and-Topic-Selection-Friends.ipynb. (Soon it will be merged in main repo branch as part of the PR https://github.com/machine-intelligence-laboratory/TopicNet/pull/98.)

Tested locally — seems like works. (But not sure about Colab, will it work here or not :sweat_smile: because Colab + TopicNet/BigARTM duo might have some kind of its own "bats in the belfry".)

Hope you are fine) Have a nice day!

**Comment by Alvant** [comment]
Ups, sure, it is not going to work in Colab yet, because the aforementioned PR also contains some other fixes in the code (vanilla `pip install topicnet` will not fetch the fixes until the PR is merged).

Well, stay tuned) I'll try notebook in Colab later.

**Comment by Alvant** [comment]
Colab now also workable:

![image](https://github.com/user-attachments/assets/3ca23fc1-cb55-4ba2-abfe-999e48b1d9a5)

@brothertook, thanks once again for the issue!
